version: "3"
services:
  mongoDB:
    image: mongo
    ports:
      - "27017:27017"
    hostname: "localhost"
    environment:
      "MONGO_INITDB_ROOT_USERNAME": "root"
      "MONGO_INITDB_ROOT_PASSWORD": "password"